# Generated by Django 3.0.5 on 2020-07-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alternative', models.CharField(choices=[('Ac', 'Activité'), ('Su', 'Substitut')], default='Ac', max_length=2)),
                ('type_activity', models.CharField(choices=[('Sp', 'Sport'), ('Lo', 'Loisir'), ('So', 'Soin')], max_length=2, null=True)),
                ('activity', models.CharField(max_length=200, null=True)),
                ('substitut', models.CharField(choices=[('P', 'Patchs'), ('PAST', 'Pastilles'), ('GM', 'Gommes à mâcher'), ('GS', 'Gommes à sucer'), ('CS', 'Comprimés sublinguaux'), ('ECIG', 'Cigarette éléctronique')], max_length=4, null=True)),
                ('nicotine', models.FloatField(null=True)),
                ('display', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type_alternative', 'activity', 'substitut', 'nicotine')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('starting_nb_cig', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cig', models.CharField(choices=[('IND', 'Cigarettes'), ('ROL', 'Tabac à rouler')], default='IND', max_length=8)),
                ('brand', models.CharField(max_length=200)),
                ('qt_paquet', models.IntegerField(default=20)),
                ('unit', models.CharField(choices=[('U', 'Unités'), ('G', 'Grammes')], default='U', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_per_cig', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('price_per_cig', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('display', models.BooleanField(default=True)),
                ('first', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type_cig', 'brand', 'qt_paquet', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.IntegerField(unique=True)),
                ('datetime_creation', models.DateTimeField()),
                ('datetime_objectif', models.DateTimeField()),
                ('respected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoCig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cig', models.DateField()),
                ('time_cig', models.TimeField()),
                ('given', models.BooleanField(default=False)),
                ('paquet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuitSoonApp.Paquet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_alter', models.DateField()),
                ('time_alter', models.TimeField()),
                ('activity_duration', models.IntegerField(null=True)),
                ('ecig_choice', models.CharField(choices=[('V', "J'ai vapoté aujourd'hui"), ('S', "J'ai démarré un nouveau flacon"), ('VS', "J'ai vapoté aujourd'hui et démarré un nouveau flacon")], max_length=2, null=True)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuitSoonApp.Alternative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trophee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_cig', models.IntegerField()),
                ('nb_jour', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nb_cig', 'nb_jour')},
            },
        ),
    ]
