# Generated by Django 3.0.5 on 2020-05-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquet',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuitSoonApp.UserProfile'),
            preserve_default=False,
        ),
    ]
