# Generated by Django 3.0.5 on 2020-09-01 12:22

import datetime
import pytz

from django.utils.timezone import make_aware
from django.db import migrations, models


def update_datetime_cig(apps, schema_editor):
    ConsoCig = apps.get_model("QuitSoonApp", "ConsoCig")
    for conso in ConsoCig.objects.all():
        naive_datetime = datetime.datetime.combine(
            conso.date_cig,
            conso.time_cig,
            )
        conso.datetime_cig = make_aware(naive_datetime, pytz.utc)
        conso.save()

def update_datetime_alter(apps, schema_editor):
    ConsoAlternative = apps.get_model("QuitSoonApp", "ConsoAlternative")
    for conso in ConsoAlternative.objects.all():
        naive_datetime = datetime.datetime.combine(
            conso.date_alter,
            conso.time_alter,
            )
        conso.datetime_alter = make_aware(naive_datetime, pytz.utc)
        conso.save()

class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0002_auto_20200728_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoalternative',
            name='datetime_alter',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(update_datetime_alter),
        migrations.AddField(
            model_name='consoalternative',
            name='user_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='consocig',
            name='datetime_cig',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(update_datetime_cig),
        migrations.AddField(
            model_name='consocig',
            name='user_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
