# Generated by Django 3.0.5 on 2020-09-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0003_auto_20200901_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoalternative',
            name='date_alter',
        ),
        migrations.RemoveField(
            model_name='consoalternative',
            name='time_alter',
        ),
        migrations.RemoveField(
            model_name='consocig',
            name='date_cig',
        ),
        migrations.RemoveField(
            model_name='consocig',
            name='time_cig',
        ),
    ]
