# Generated by Django 3.0.5 on 2020-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0003_auto_20200806_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoalternative',
            name='user_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='consocig',
            name='user_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
