# Generated by Django 3.0.5 on 2020-05-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0003_alternative_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='consoalternative',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='consocig',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='objectif',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paquet',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trophee',
            old_name='id_user',
            new_name='user',
        ),
    ]
