# Generated by Django 3.0.5 on 2020-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0004_auto_20200902_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoalternative',
            name='ecig_choice',
        ),
        migrations.AlterField(
            model_name='alternative',
            name='substitut',
            field=models.CharField(choices=[('P', 'Patchs'), ('PAST', 'Pastilles'), ('GM', 'Gommes à mâcher'), ('GS', 'Gommes à sucer'), ('CS', 'Comprimés sublinguaux')], max_length=4, null=True),
        ),
    ]
