# Generated by Django 3.0.5 on 2020-05-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0006_auto_20200513_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consoalternative',
            old_name='id_alter',
            new_name='alternative',
        ),
        migrations.RenameField(
            model_name='consoalternative',
            old_name='duree',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='consocig',
            old_name='id_paquet',
            new_name='paquet',
        ),
    ]
