# Generated by Django 3.0.5 on 2020-05-18 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuitSoonApp', '0007_auto_20200513_1136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paquet',
            unique_together={('user', 'type_cig', 'brand', 'qt_paquet', 'price')},
        ),
    ]
