# Generated by Django 3.0.5 on 2020-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0008_auto_20200518_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquet',
            name='price_per_cig',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
