# Generated by Django 3.0.5 on 2020-05-20 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuitSoonApp', '0009_paquet_price_per_cig'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='substitut',
            field=models.CharField(choices=[('P24', 'Patchs(24h)'), ('P16', 'Patchs(16h)'), ('PAST', 'Pastilles'), ('GM', 'Gommes à mâcher'), ('GS', 'Gommes à sucer'), ('CS', 'Comprimés sublinguaux'), ('ECIG', 'Cigarette éléctronique')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='alternative',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together={('user', 'type_alternative', 'alternative', 'substitut', 'nicotine')},
        ),
    ]
