# Generated by Django 3.0.5 on 2020-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0011_alternative_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='substitut',
            field=models.CharField(choices=[('P24', 'Patchs(24h)'), ('P16', 'Patchs(16h)'), ('PAST', 'Pastilles'), ('GM', 'Gommes à mâcher'), ('GS', 'Gommes à sucer'), ('c', 'Comprimés sublinguaux'), ('ECIG', 'Cigarette éléctronique')], max_length=200, null=True),
        ),
    ]
