# Generated by Django 3.0.5 on 2020-05-21 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuitSoonApp', '0013_auto_20200521_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together={('user', 'type_alternative', 'alternative', 'substitut', 'nicotine')},
        ),
    ]
