# Generated by Django 3.0.5 on 2020-05-21 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuitSoonApp', '0015_auto_20200521_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='alternative',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='type_alternative',
            field=models.CharField(choices=[('Sp', 'Sport'), ('Lo', 'Loisir'), ('So', 'Soin'), ('Su', 'Substitut')], default='Sp', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together={('user', 'type_alternative', 'alternative', 'substitut', 'nicotine')},
        ),
        migrations.RemoveField(
            model_name='alternative',
            name='activity',
        ),
    ]
