# Generated by Django 3.0.5 on 2020-05-21 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuitSoonApp', '0016_auto_20200521_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='activity',
            field=models.CharField(choices=[('Sp', 'Sport'), ('Lo', 'Loisir'), ('So', 'Soin')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='substitut',
            field=models.CharField(choices=[('P24', 'Patchs(24h)'), ('P16', 'Patchs(16h)'), ('PAST', 'Pastilles'), ('GM', 'Gommes à mâcher'), ('GS', 'Gommes à sucer'), ('CS', 'Comprimés sublinguaux'), ('ECIG', 'Cigarette éléctronique')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='type_alternative',
            field=models.CharField(choices=[('Ac', 'Activité'), ('Su', 'Substitut')], default='Ac', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='alternative',
            unique_together={('user', 'type_alternative', 'activity', 'substitut', 'nicotine')},
        ),
        migrations.RemoveField(
            model_name='alternative',
            name='alternative',
        ),
    ]
