# Generated by Django 3.0.5 on 2020-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0019_auto_20200529_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoalternative',
            name='ecig_choice',
            field=models.CharField(choices=[('V', "J'ai vapoté aujourd'hui"), ('S', "J'ai démarré un nouveau flacon"), ('VS', "J'ai vapoté aujourd'hui et démarré un nouveau flacon")], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paquet',
            name='type_cig',
            field=models.CharField(choices=[('IND', 'Cigarettes'), ('ROL', 'Tabac à rouler')], default='IND', max_length=8),
        ),
    ]
