# Generated by Django 3.0.5 on 2020-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0020_auto_20200601_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquet',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
