# Generated by Django 3.0.5 on 2020-06-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuitSoonApp', '0022_auto_20200619_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquet',
            name='g_per_cig',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paquet',
            name='price_per_cig',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
